### Schema

CREATE DATABASE food_db;
USE food_db;

CREATE TABLE food
(
	id int NOT NULL AUTO_INCREMENT,
	description varchar(255) NOT NULL,
	is_eaten BOOLEAN DEFAULT false,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);
